if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SFML source directory was not provided")
endif()

set(SFML_WINDOW_CONTROLLER
    "${SOURCE_DIR}/src/SFML/Window/macOS/SFWindowController.mm"
)
if(NOT EXISTS "${SFML_WINDOW_CONTROLLER}")
    message(FATAL_ERROR "SFML 3.1.0 macOS window controller was not found")
endif()

file(READ "${SFML_WINDOW_CONTROLLER}" SFML_WINDOW_CONTROLLER_SOURCE)

set(SFML_LOW_DPI_ASSIGNMENT "        m_highDpi       = NO;")
set(SFML_HIGH_DPI_ASSIGNMENT
    "        m_highDpi       = YES; // Emerald Rogue Assistant: render the OpenGL surface at native Retina resolution."
)
set(SFML_LOW_DPI_VIEW "fullscreen:NO highDpi:NO]")
set(SFML_HIGH_DPI_VIEW "fullscreen:NO highDpi:m_highDpi]")

string(REGEX MATCHALL "m_highDpi       = NO" SFML_LOW_DPI_ASSIGNMENTS "${SFML_WINDOW_CONTROLLER_SOURCE}")
string(REGEX MATCHALL "m_highDpi       = YES" SFML_HIGH_DPI_ASSIGNMENTS
             "${SFML_WINDOW_CONTROLLER_SOURCE}")
list(LENGTH SFML_LOW_DPI_ASSIGNMENTS SFML_LOW_DPI_ASSIGNMENT_COUNT)
list(LENGTH SFML_HIGH_DPI_ASSIGNMENTS SFML_HIGH_DPI_ASSIGNMENT_COUNT)
string(FIND "${SFML_WINDOW_CONTROLLER_SOURCE}" "${SFML_LOW_DPI_VIEW}" SFML_LOW_DPI_VIEW_INDEX)
string(FIND "${SFML_WINDOW_CONTROLLER_SOURCE}" "${SFML_HIGH_DPI_VIEW}" SFML_HIGH_DPI_VIEW_INDEX)

if(SFML_LOW_DPI_ASSIGNMENT_COUNT EQUAL 2 AND NOT SFML_LOW_DPI_VIEW_INDEX EQUAL -1)
    string(REPLACE "${SFML_LOW_DPI_ASSIGNMENT}" "${SFML_HIGH_DPI_ASSIGNMENT}"
                   SFML_WINDOW_CONTROLLER_SOURCE "${SFML_WINDOW_CONTROLLER_SOURCE}")
    string(REPLACE "${SFML_LOW_DPI_VIEW}" "${SFML_HIGH_DPI_VIEW}"
                   SFML_WINDOW_CONTROLLER_SOURCE "${SFML_WINDOW_CONTROLLER_SOURCE}")
    file(WRITE "${SFML_WINDOW_CONTROLLER}" "${SFML_WINDOW_CONTROLLER_SOURCE}")
elseif(NOT SFML_LOW_DPI_ASSIGNMENT_COUNT EQUAL 0 OR
       NOT SFML_HIGH_DPI_ASSIGNMENT_COUNT EQUAL 2 OR
       NOT SFML_LOW_DPI_VIEW_INDEX EQUAL -1 OR
       SFML_HIGH_DPI_VIEW_INDEX EQUAL -1)
    message(FATAL_ERROR "SFML 3.1.0 macOS high-DPI patch no longer matches the pinned source")
endif()
