set(
  ROGUE_PACKAGE_PLATFORM
  ""
  CACHE STRING
  "Package platform suffix; release presets set this value"
)

if(ROGUE_PACKAGE_PLATFORM STREQUAL "")
  if(WIN32)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(ROGUE_PACKAGE_PLATFORM windows-x64)
    else()
      set(ROGUE_PACKAGE_PLATFORM windows-unsupported)
    endif()
  elseif(APPLE)
    set(ROGUE_PACKAGE_PLATFORM macos-${CMAKE_SYSTEM_PROCESSOR})
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(ROGUE_PACKAGE_PLATFORM linux-${CMAKE_SYSTEM_PROCESSOR})
  else()
    set(ROGUE_PACKAGE_PLATFORM ${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR})
  endif()
endif()

if(ROGUE_PACKAGE_PLATFORM STREQUAL "windows-x64")
  if(NOT WIN32 OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "windows-x64 packages require a 64-bit Windows toolchain")
  endif()
elseif(ROGUE_PACKAGE_PLATFORM STREQUAL "macos-arm64")
  if(NOT APPLE)
    message(FATAL_ERROR "macos-arm64 packages require an arm64-only macOS toolchain")
  endif()
  if(CMAKE_OSX_ARCHITECTURES)
    if(NOT CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
      message(FATAL_ERROR "macos-arm64 packages require an arm64-only macOS toolchain")
    endif()
  elseif(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
    message(FATAL_ERROR "macos-arm64 packages require an arm64-only macOS toolchain")
  endif()
elseif(ROGUE_PACKAGE_PLATFORM STREQUAL "linux-x86_64")
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR
     NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
    message(FATAL_ERROR "linux-x86_64 packages require a Linux x86_64 toolchain")
  endif()
endif()

set(CPACK_PACKAGE_NAME RogueAssistant)
set(CPACK_PACKAGE_VENDOR "Emerald Rogue Assistant Project")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_FILE_NAME RogueAssistant-${ROGUE_ASSISTANT_BUILD_LABEL}-${ROGUE_PACKAGE_PLATFORM})
set(CPACK_PACKAGE_DIRECTORY ${CMAKE_BINARY_DIR}/packages)
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_COMPONENTS_ALL RogueAssistant)
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_COMPONENT_ROGUEASSISTANT_DISPLAY_NAME "${ROGUE_ASSISTANT_DISPLAY_NAME}")
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)

if(WIN32)
  set(CPACK_GENERATOR ZIP)
elseif(APPLE)
  # Releases use the DMG from package.sh. This archive is for local install checks.
  set(CPACK_GENERATOR ZIP)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CPACK_GENERATOR TGZ)
else()
  message(FATAL_ERROR "Packaging is unsupported on ${CMAKE_SYSTEM_NAME}")
endif()

include(CPack)
