if(NOT DEFINED ROGUE_VERSION_OUTPUT OR ROGUE_VERSION_OUTPUT STREQUAL "")
  message(FATAL_ERROR "ROGUE_VERSION_OUTPUT must name the output file")
endif()

include(${CMAKE_CURRENT_LIST_DIR}/Version.cmake)
file(WRITE ${ROGUE_VERSION_OUTPUT} "${ROGUE_ASSISTANT_VERSION}\n")
if(DEFINED ROGUE_BUILD_LABEL_OUTPUT)
  file(WRITE "${ROGUE_BUILD_LABEL_OUTPUT}" "${ROGUE_ASSISTANT_BUILD_LABEL}\n")
endif()
